### ISSUE TITLE
This mod seems to have done nothing

### ISSUE THREAD

**Issue by smilepeak** [AndreyMrovol/LethalLightsOut#1]
I installed this MOD but there were no changes

**Comment by AndreyMrovol** [comment]
Hey, this mod turns off `Fancy lamps` and `Apparatus` light sources on ship (so they don't cast shadows and cause lags) - have you checked if that functionality works?

**Comment by smilepeak** [comment]
Ah！！I thought this MOD was to turn off the surveillance cameras on the ship
The function you said does work
sorry！！

**Comment by AndreyMrovol** [comment]
No problem, I'll write a better README 😅
